In [1]:
import os

def get_subject(filename):
    fis = os.path.basename(filename)
    return fis.split("sults")[1].split("_")[0]

def get_task(filename):
    fis = os.path.basename(filename)
    return fis.split("_")[1].replace(".mat", '')


def get_files(rootdir = 'task1 - NR/Matlab files/', task = 'NR'):
    all_files = []
    for file in os.listdir(rootdir):
        if file.endswith(task+".mat"):
            file_path = os.path.join(rootdir, file)
            subject = get_subject(file_path)
            # exclude YMH due to incomplete data because of dyslexia
            if subject == 'YMH':
                continue
            all_files.append(file_path)
    return all_files

all_files = get_files()
all_files

['task1 - NR/Matlab files/resultsYHS_NR.mat',
 'task1 - NR/Matlab files/resultsYDR_NR.mat',
 'task1 - NR/Matlab files/resultsYMD_NR.mat',
 'task1 - NR/Matlab files/resultsYRH_NR.mat',
 'task1 - NR/Matlab files/resultsYRK_NR.mat',
 'task1 - NR/Matlab files/resultsYSD_NR.mat',
 'task1 - NR/Matlab files/resultsYFR_NR.mat',
 'task1 - NR/Matlab files/resultsYDG_NR.mat',
 'task1 - NR/Matlab files/resultsYIS_NR.mat',
 'task1 - NR/Matlab files/resultsYFS_NR.mat',
 'task1 - NR/Matlab files/resultsYMS_NR.mat',
 'task1 - NR/Matlab files/resultsYAG_NR.mat',
 'task1 - NR/Matlab files/resultsYLS_NR.mat',
 'task1 - NR/Matlab files/resultsYRP_NR.mat',
 'task1 - NR/Matlab files/resultsYSL_NR.mat',
 'task1 - NR/Matlab files/resultsYTL_NR.mat',
 'task1 - NR/Matlab files/resultsYAK_NR.mat',
 'task1 - NR/Matlab files/resultsYAC_NR.mat']

In [2]:
import numpy as np
import h5py
import pandas as pd
from tqdm import tqdm

import data_loading_helpers as dh

In [3]:
f = h5py.File(all_files[0])
list(f.keys())

['#refs#', 'sentenceData']

In [4]:
sentence_data = f['sentenceData']
list(sentence_data.keys())

['allFixations',
 'content',
 'mean_a1',
 'mean_a1_diff',
 'mean_a2',
 'mean_a2_diff',
 'mean_b1',
 'mean_b1_diff',
 'mean_b2',
 'mean_b2_diff',
 'mean_g1',
 'mean_g1_diff',
 'mean_g2',
 'mean_g2_diff',
 'mean_t1',
 'mean_t1_diff',
 'mean_t2',
 'mean_t2_diff',
 'omissionRate',
 'rawData',
 'word',
 'wordbounds']

In [5]:
wordData = sentence_data['word']
list(wordData.keys())

AttributeError: 'Dataset' object has no attribute 'keys'

In [6]:
wordData

<HDF5 dataset "word": shape (349, 1), type "|O">

In [7]:
len(wordData)

349

In [8]:
wordData[0]

array([<HDF5 object reference>], dtype=object)

In [9]:
len(wordData[0])

1

In [10]:
wordData[0][0]

<HDF5 object reference>

In [11]:
wordData[0].shape

(1,)

In [12]:
wordData.dtype

dtype('O')

In [13]:
wordData.attrs.keys()

<KeysViewHDF5 []>

In [14]:
f[wordData[0][0]]

<HDF5 group "/#refs#/vNb" (96 members)>

In [15]:
refs = f['#refs#']
refs

<HDF5 group "/#refs#" (100006 members)>

In [16]:
refs.keys()

<KeysViewHDF5 ['#a', '#b', '#c', '#d', '#e', '0', '00', '00b', '00c', '00d', '00e', '00f', '00g', '00h', '00i', '00j', '00k', '00l', '00m', '00n', '00o', '00p', '00q', '00r', '00s', '00t', '00u', '00v', '00w', '00x', '00y', '00z', '01', '01b', '01c', '01d', '01e', '01f', '01g', '01h', '01i', '01j', '01k', '01l', '01m', '01n', '01o', '01p', '01q', '01r', '01s', '01t', '01u', '01v', '01w', '01x', '01y', '01z', '02', '02b', '02c', '02d', '02e', '02f', '02g', '02h', '02i', '02j', '02k', '02l', '02m', '02n', '02o', '02p', '02q', '02r', '02s', '02t', '02u', '02v', '02w', '02x', '02y', '02z', '03', '03b', '03c', '03d', '03e', '03f', '03g', '03h', '03i', '03j', '03k', '03l', '03m', '03n', '03o', '03p', '03q', '03r', '03s', '03t', '03u', '03v', '03w', '03x', '03y', '03z', '04', '04b', '04c', '04d', '04e', '04f', '04g', '04h', '04i', '04j', '04k', '04l', '04m', '04n', '04o', '04p', '04q', '04r', '04s', '04t', '04u', '04v', '04w', '04x', '04y', '04z', '05', '05b', '05c', '05d', '05e', '05f', '05g

In [17]:
f['#refs#/vNb'].keys()

<KeysViewHDF5 ['FFD', 'FFD_a1', 'FFD_a1_diff', 'FFD_a2', 'FFD_a2_diff', 'FFD_b1', 'FFD_b1_diff', 'FFD_b2', 'FFD_b2_diff', 'FFD_g1', 'FFD_g1_diff', 'FFD_g2', 'FFD_g2_diff', 'FFD_pupilsize', 'FFD_t1', 'FFD_t1_diff', 'FFD_t2', 'FFD_t2_diff', 'GD', 'GD_a1', 'GD_a1_diff', 'GD_a2', 'GD_a2_diff', 'GD_b1', 'GD_b1_diff', 'GD_b2', 'GD_b2_diff', 'GD_g1', 'GD_g1_diff', 'GD_g2', 'GD_g2_diff', 'GD_pupilsize', 'GD_t1', 'GD_t1_diff', 'GD_t2', 'GD_t2_diff', 'GPT', 'GPT_a1', 'GPT_a1_diff', 'GPT_a2', 'GPT_a2_diff', 'GPT_b1', 'GPT_b1_diff', 'GPT_b2', 'GPT_b2_diff', 'GPT_g1', 'GPT_g1_diff', 'GPT_g2', 'GPT_g2_diff', 'GPT_pupilsize', 'GPT_t1', 'GPT_t1_diff', 'GPT_t2', 'GPT_t2_diff', 'SFD', 'SFD_a1', 'SFD_a1_diff', 'SFD_a2', 'SFD_a2_diff', 'SFD_b1', 'SFD_b1_diff', 'SFD_b2', 'SFD_b2_diff', 'SFD_g1', 'SFD_g1_diff', 'SFD_g2', 'SFD_g2_diff', 'SFD_pupilsize', 'SFD_t1', 'SFD_t1_diff', 'SFD_t2', 'SFD_t2_diff', 'TRT', 'TRT_a1', 'TRT_a1_diff', 'TRT_a2', 'TRT_a2_diff', 'TRT_b1', 'TRT_b1_diff', 'TRT_b2', 'TRT_b2_diff', 

In [18]:
f[wordData[0][0]].keys()

<KeysViewHDF5 ['FFD', 'FFD_a1', 'FFD_a1_diff', 'FFD_a2', 'FFD_a2_diff', 'FFD_b1', 'FFD_b1_diff', 'FFD_b2', 'FFD_b2_diff', 'FFD_g1', 'FFD_g1_diff', 'FFD_g2', 'FFD_g2_diff', 'FFD_pupilsize', 'FFD_t1', 'FFD_t1_diff', 'FFD_t2', 'FFD_t2_diff', 'GD', 'GD_a1', 'GD_a1_diff', 'GD_a2', 'GD_a2_diff', 'GD_b1', 'GD_b1_diff', 'GD_b2', 'GD_b2_diff', 'GD_g1', 'GD_g1_diff', 'GD_g2', 'GD_g2_diff', 'GD_pupilsize', 'GD_t1', 'GD_t1_diff', 'GD_t2', 'GD_t2_diff', 'GPT', 'GPT_a1', 'GPT_a1_diff', 'GPT_a2', 'GPT_a2_diff', 'GPT_b1', 'GPT_b1_diff', 'GPT_b2', 'GPT_b2_diff', 'GPT_g1', 'GPT_g1_diff', 'GPT_g2', 'GPT_g2_diff', 'GPT_pupilsize', 'GPT_t1', 'GPT_t1_diff', 'GPT_t2', 'GPT_t2_diff', 'SFD', 'SFD_a1', 'SFD_a1_diff', 'SFD_a2', 'SFD_a2_diff', 'SFD_b1', 'SFD_b1_diff', 'SFD_b2', 'SFD_b2_diff', 'SFD_g1', 'SFD_g1_diff', 'SFD_g2', 'SFD_g2_diff', 'SFD_pupilsize', 'SFD_t1', 'SFD_t1_diff', 'SFD_t2', 'SFD_t2_diff', 'TRT', 'TRT_a1', 'TRT_a1_diff', 'TRT_a2', 'TRT_a2_diff', 'TRT_b1', 'TRT_b1_diff', 'TRT_b2', 'TRT_b2_diff', 

In [19]:
rawData = sentence_data['rawData']
rawData

<HDF5 dataset "rawData": shape (349, 1), type "|O">

In [20]:
rawData[0][0]

<HDF5 object reference>

In [21]:
f[rawData[0][0]]

<HDF5 dataset "Of": shape (3274, 105), type "<f8">

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.


In [22]:
contentData = sentence_data['content']
contentData

<HDF5 dataset "content": shape (349, 1), type "|O">

In [23]:
f[contentData[0][0]]

<HDF5 dataset "b": shape (152, 1), type "<u2">

In [24]:
omissionR = sentence_data['omissionRate']
omissionR

<HDF5 dataset "omissionRate": shape (349, 1), type "|O">

In [25]:
f[omissionR[0][0]]

<HDF5 dataset "Jmx": shape (1, 1), type "<f8">

In [26]:
f[wordData[0][0]]

<HDF5 group "/#refs#/vNb" (96 members)>

In [27]:
f[wordData[0][0]]['content']

<HDF5 dataset "content": shape (25, 1), type "|O">

In [28]:
f[wordData[1][0]]['content']

<HDF5 dataset "content": shape (17, 1), type "|O">

In [29]:
f[f[wordData[0][0]]['content'][0][0]]

<HDF5 dataset "wNb": shape (5, 1), type "<u2">

In [30]:
tmp = []
for c in f[f[wordData[0][0]]['content'][0][0]]:
    tmp.append(chr(c[0]))
tmp

['H', 'e', 'n', 'r', 'y']

In [31]:
len(f[wordData[0][0]]['content'])

25

In [32]:
# note that the original code gets the sentence from contentData, not wordData->content (note that they are different)
tmp = []
for i in range(len(f[wordData[0][0]]['content'])):
    tmp.append(''.join(chr(c[0]) for c in f[ f[wordData[0][0]] ['content'][i][0] ]))
tmp

['Henry',
 'Ford,',
 'with',
 'his',
 'son',
 'Edsel,',
 'founded',
 'the',
 'Ford',
 'Foundation',
 'in',
 '1936',
 'as',
 'a',
 'local',
 'philanthropic',
 'organization',
 'with',
 'a',
 'broad',
 'charter',
 'to',
 'promote',
 'human',
 'welfare.']

In [33]:
# checking the output of dh.extrace_word_level_data
dh.extract_word_level_data(f, f[wordData[0][0]])

{0: {'RAW_EEG': [array([[ 1.846 ,  2.088 ,  5.035 , ...,  5.727 ,  6.117 ,  0.    ],
          [ 1.502 ,  1.345 ,  4.44  , ...,  4.89  ,  5.297 ,  0.    ],
          [ 1.349 ,  0.6616,  3.584 , ...,  3.79  ,  4.22  ,  0.    ],
          ...,
          [ 4.965 ,  1.364 , -0.4277, ...,  2.297 ,  2.541 ,  0.    ],
          [ 5.64  ,  2.365 ,  0.3584, ...,  3.342 ,  3.824 ,  0.    ],
          [ 6.535 ,  3.51  ,  1.194 , ...,  4.45  ,  5.082 ,  0.    ]],
         dtype=float16)],
  'RAW_ET': [array([[1.5888700e+06, 1.3720642e+02, 1.8030183e+02, 3.2110093e+03],
          [1.5888720e+06, 1.3710092e+02, 1.8020091e+02, 3.2090183e+03],
          [1.5888740e+06, 1.3729816e+02, 1.8010092e+02, 3.2080093e+03],
          [1.5888760e+06, 1.3779541e+02, 1.8000092e+02, 3.2060183e+03],
          [1.5888780e+06, 1.3819632e+02, 1.7990092e+02, 3.2050093e+03],
          [1.5888800e+06, 1.3869540e+02, 1.7980092e+02, 3.2030183e+03],
          [1.5888820e+06, 1.3899724e+02, 1.7970093e+02, 3.2020093e+03],
    

In [34]:
f[contentData[0][0]]

<HDF5 dataset "b": shape (152, 1), type "<u2">

In [35]:
f[wordData[0][0]]['nFixations']

<HDF5 dataset "nFixations": shape (25, 1), type "|O">

In [36]:
f[wordData[0][0]]['rawEEG']

<HDF5 dataset "rawEEG": shape (25, 1), type "|O">

In [37]:
f[wordData[0][0]]['rawEEG'][0]

array([<HDF5 object reference>], dtype=object)

In [38]:
f[f[wordData[0][0]]['rawEEG'][0][0]]

<HDF5 dataset "9Ob": shape (1, 1), type "|O">

In [39]:
f[ f[f[wordData[0][0]]['rawEEG'][0][0]] [0][0] ]

<HDF5 dataset "0Ob": shape (57, 105), type "<f8">

In [40]:
f[ f[f[wordData[0][0]]['rawEEG'][1][0]] [0][0] ]

<HDF5 dataset "bPb": shape (113, 105), type "<f8">

In [41]:
f[ f[f[wordData[0][0]]['rawEEG'][3][0]] [0][0] ] # does not work with 2 for some reason

<HDF5 dataset "dPb": shape (65, 105), type "<f8">

In [42]:
# ^ note that the second dimension is the number of electrodes

In [43]:
f[ f[f[wordData[0][0]]['rawEEG'][0][0]] [0][0] ] [:]

array([[ 1.84554693,  2.08847237,  5.03340152, ...,  5.72541156,
         6.11817731,  0.        ],
       [ 1.50239113,  1.34443177,  4.43950105, ...,  4.89132924,
         5.29716068,  0.        ],
       [ 1.34828323,  0.66154148,  3.58333253, ...,  3.78811114,
         4.21997168,  0.        ],
       ...,
       [ 4.96662915,  1.36409182, -0.42762791, ...,  2.29663653,
         2.54159998,  0.        ],
       [ 5.64256348,  2.36530222,  0.35840082, ...,  3.3417879 ,
         3.82498527,  0.        ],
       [ 6.53625084,  3.5094776 ,  1.19388481, ...,  4.44731991,
         5.0811266 ,  0.        ]])

In [44]:
f[wordData[0][0]]['fixPositions']

<HDF5 dataset "fixPositions": shape (25, 1), type "|O">

In [45]:
f[ f[wordData[0][0]]['fixPositions'] [0][0] ]

<HDF5 dataset "VNb": shape (1, 1), type "<f8">

In [46]:
f[ f[wordData[0][0]]['fixPositions'] [0][0] ] [:]

array([[3.]])

In [47]:
f[wordData[0][0]]['nFixations']

<HDF5 dataset "nFixations": shape (25, 1), type "|O">

In [48]:
f[ f[wordData[0][0]]['nFixations'] [0][0] ]

<HDF5 dataset "kOb": shape (1, 1), type "<f8">

In [49]:
f[ f[wordData[0][0]]['nFixations'] [0][0] ] [:]

array([[1.]])

In [50]:
f[ f[wordData[0][0]]['fixPositions'] [2][0] ] [:]

array([0, 0], dtype=uint64)

In [51]:
f[ f[wordData[0][0]]['nFixations'] [2][0] ] [:] # it would seem the 3rd word in the 1st sentence is invalid

array([0, 0], dtype=uint64)

In [52]:
f[ f[wordData[0][0]]['fixPositions'] [4][0] ] [:]

array([[ 4.],
       [17.],
       [28.]])

In [53]:
f[ f[wordData[0][0]]['nFixations'] [4][0] ] [:]

array([[3.]])

In [54]:
# ^ unless malformed, nFixations is a 1x1 array containing the number of fixations

In [55]:
# ^ also, note that a fixation position seems to be only described by one number, not two (wtf??)

In [56]:
# next, check datasets that could potentially contain information about the fixation timings

In [57]:
f[wordData[0][0]]['rawET']

<HDF5 dataset "rawET": shape (25, 1), type "|O">

In [58]:
f[ f[wordData[0][0]]['rawET'] [0][0] ]

<HDF5 dataset "QPb": shape (1, 1), type "|O">

In [59]:
f[ f[wordData[0][0]]['rawET'] [1][0] ]

<HDF5 dataset "SPb": shape (1, 1), type "|O">

In [60]:
f[ f[wordData[0][0]]['rawET'] [2][0] ]

<HDF5 dataset "a": shape (2,), type "<u8">

In [61]:
f[ f[wordData[0][0]]['rawET'] [2][0] ] [:]

array([0, 0], dtype=uint64)

In [62]:
f[ f[ f[wordData[0][0]]['rawET'] [0][0] ][0][0] ]

<HDF5 dataset "RPb": shape (57, 4), type "<f8">

In [63]:
f[ f[ f[wordData[0][0]]['rawET'] [1][0] ][0][0] ]

<HDF5 dataset "TPb": shape (113, 4), type "<f8">

In [64]:
f[ f[ f[wordData[0][0]]['rawET'] [0][0] ][0][0] ] [:]

array([[1.58886998e+06, 1.37206418e+02, 1.80301834e+02, 3.21100917e+03],
       [1.58887198e+06, 1.37100918e+02, 1.80200918e+02, 3.20901835e+03],
       [1.58887398e+06, 1.37298164e+02, 1.80100918e+02, 3.20800918e+03],
       [1.58887598e+06, 1.37795405e+02, 1.80000919e+02, 3.20601838e+03],
       [1.58887798e+06, 1.38196321e+02, 1.79900920e+02, 3.20500920e+03],
       [1.58887998e+06, 1.38695398e+02, 1.79800920e+02, 3.20301841e+03],
       [1.58888198e+06, 1.38997237e+02, 1.79700921e+02, 3.20200921e+03],
       [1.58888398e+06, 1.39297235e+02, 1.79700000e+02, 3.20100922e+03],
       [1.58888598e+06, 1.39399078e+02, 1.79799078e+02, 3.19901845e+03],
       [1.58888798e+06, 1.39499077e+02, 1.79899077e+02, 3.19800923e+03],
       [1.58888998e+06, 1.39599076e+02, 1.79900000e+02, 3.19601848e+03],
       [1.58889198e+06, 1.39699075e+02, 1.80098151e+02, 3.19500925e+03],
       [1.58889398e+06, 1.39600925e+02, 1.80000925e+02, 3.19301851e+03],
       [1.58889598e+06, 1.39302778e+02, 1.79603704e